### ISSUE TITLE
Taxonomy term splitting in 4.2 - action maybe needed?

### ISSUE THREAD

**Issue by kuchenundkakao** [not-only-code/qtranslate-slug#105]
Hi!
With the Wordpress 4.2 Update coming up, i saw that there is an update coming for shared terms. 
You can see it here: 
https://make.wordpress.org/core/2015/02/16/taxonomy-term-splitting-in-4-2-a-developer-guide/
As qtranslate slug uses the term id, this maybe could become a problem. Please have a look.

Happy Coding,
Kuchenundkakao

**Comment by LC43** [comment]
Hi @kuchenundkakao , thanks for the heads up! This will be a good opportunity to fix all the term related issues. @not-only-code , how's your schedule?

**Comment by LC43** [comment]
well, i think the worst didn't happen. I've had a site that needed some tags/categories to be created again. most problems could be solved by doing this. thanks @kuchenundkakao !
