### ISSUE TITLE
qts_split, qts_use & qTranslate-X 3.1

### ISSUE THREAD

**Issue by johnclause** [not-only-code/qtranslate-slug#107]
Hi Pedro, I have just discovered that -slug seem to override the behaviour of functions `_split` and `_use`, which I did not expect. Please, read release notes https://wordpress.org/support/topic/release-31-notes for version 3.1 of qTranslate-X. I believe it makes -X to be incompatible with -slug. You need to remove all customization of `qtrans_` functions for -X integration. Besides, as far as I understood, what you optimized in your custom functions is already done in -X as well. If you can think of other improvements for `_split`, and `_use`, let me know I will implement them within -X, but -slug should not duplicate the same functions. In the past, when qTranslate was not available for modifications, it made good sense, but with -X now, all such customizations need to be removed. We can change the code of -X with any of your improvements. Please, let me know what else you improved, which I do not have yet in -X.
I am sorry about this, I had no idea that those were customized in -slug, otherwise I would coordinate this change with you.

**Comment by LC43** [comment]
nice to see some those changes! i've reverted ( its in the wp repo, for now)
