### ISSUE TITLE
Lnaguage switcher does not work for custom post type archive

### ISSUE THREAD

**Issue by pabloselin** [not-only-code/qtranslate-slug#11]
Hi, it seems that the language switcher is not working when I'm in a custom post type archive page.

The function returns links like this:

http://example.com/en?post_type=ptypename&p=postid

You can see the issue here:

http://acllahuasi.com/en/ventas/ 

when you look at the url that the language switcher is returning that weird stuff.

Thanks for your work by the way, the other stuff is working great!

**Comment by not-only-code** [comment]
Is this issue https://github.com/not-only-code/qtranslate-slug/issues/3

I close this issue.
