### ISSUE TITLE
Category slug not saved

### ISSUE THREAD

**Issue by hamstelfo** [not-only-code/qtranslate-slug#116]
Hello all,
I'm getting problems with the category slugs. I can not save them (I fill the fields, save, get no errors, but the fields are still empty --> See the image below):

I have:

Wordpress 4.3.1
qTranslate slug 1.1.17
qTranslate-X 3.4.6.4
Woocommerce 2.4.7
Woocommerce & qTranslate-X 1.3
Woocommerce Customizer 2.1.1
Yoast SEO 2.3.5
Yoast SeO & qTranslate-X 1.1

Any idea? Thanks!

Rubén P.

![category-slug-not-saved](https://cloud.githubusercontent.com/assets/4498298/10687333/a9c0b252-796c-11e5-95d8-1a7eabc0d603.png)

**Comment by LC43** [comment]
Hi, you are right, let me check

**Comment by hamstelfo** [comment]
Hi, did you find any solution? Thank you very much!

**Comment by LC43** [comment]
hi @hamstelfo , have you tried cloning this repo? i've tested and it  seems working fine with the 4.3.1 and 4.4.

qts ( github )
qtranslate-x ( latest: 3.4.6.4 )
wordpress: 4.3.1 and 4.4

**Comment by LC43** [comment]
@hamstelfo are you there? can you try the new version on wp.org? thanks!

**Comment by hamstelfo** [comment]
Hi Pedro,

Sorry, we finally gave up this for the moment.. Maybe we'll resume the work
in the future. Thank you anyway.

Rubén P.

2016-01-21 6:28 GMT+01:00 Pedro de Carvalho notifications@github.com:

> @hamstelfo https://github.com/hamstelfo are you there? can you try the
> new version on wp.org? thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/not-only-code/qtranslate-slug/issues/116#issuecomment-173458289
> .

## 

..hamstelfo

**Comment by LC43** [comment]
ok! i'm closing this for now then.
