### ISSUE TITLE
Termmeta to be included into core... please Check ;)

### ISSUE THREAD

**Issue by kuchenundkakao** [not-only-code/qtranslate-slug#117]
https://make.wordpress.org/core/2015/09/22/preparing-your-plugins-and-your-client-sites-for-termmeta/

**Comment by LC43** [comment]
thanks @kuchenundkakao !

**Comment by LC43** [comment]
alright, so we just needed ( i think!) to stop dropping our own metadata table from database. it seems wp will use the exact names and database scheme! they also add cache and other things nice, so everybody wins!
