### ISSUE TITLE
subpages don't work (404)

### ISSUE THREAD

**Issue by LC43** [not-only-code/qtranslate-slug#123]
with the latest version ( 0b9929c2c08e9e1225d44e79a8f5bcdd129906a5 ) subpages return 404.

the immediate pages are working fine.

eg
/page-1/sub-page-2/ -> 404
/page-1/                    -> 200

doesn't matter if main language or not.

**Comment by ghost** [comment]
You probably didn't update page slugs, had same issue.

**Comment by LC43** [comment]
i have to try that @ghost , i thought i redid the permalinks...

**Comment by LC43** [comment]
fixed in 808247fc32fb3c276182f92b39826c872175ce4e
