### ISSUE TITLE
Breaks Woocommerce category

### ISSUE THREAD

**Issue by The3IC** [not-only-code/qtranslate-slug#129]
Hi,

Trying to take qTranslate slug into use but finding a problem with (some) Woocommerce product category pages. 

Symptoms:
- the category is not shown, but instead the category URL is redirected to the category picture

Seems to be somehow connected to naming of the category image?

WP 4.7.1, slug 1.1.18, qTranslate 3.4.6.8, Woo+qT 1.3

**Comment by LC43** [comment]
Hi @The3IC , i've pushed a new branch that  should fix your structure. can you test please?

**Comment by The3IC** [comment]
Hi, yes this seems to have fixed the issue, now that I add a categroy image with the same name as the category, the category displays OK.
