### ISSUE TITLE
error on activation

### ISSUE THREAD

**Issue by puntonero** [not-only-code/qtranslate-slug#132]
hi, 
I get error message after plugin activation.
Looking inside apache error log I found this:
` Undefined variable: max_index_length in /xxx/NetBeansProjects/xxx/wordpress/wp-content/plugins/qtranslate-slug/includes/termmeta-core.php on line 24, referer: http://xxx/wp-admin/plugins.php
`
Of course the SQL query has problem due the missing definition of **max_index_length**.
To fix it you need to add max_index_length at the beginning of install_term_meta_table function as the reference wordpress file [schema.php](https://core.trac.wordpress.org/browser/tags/4.7/src/wp-admin/includes/schema.php#L52)

I hope this helps
bye

**Comment by kuchenundkakao** [comment]
Which version of Wordpress are you using? The Term Meta Table should exist already if you are on an actual version of Wordpress...

**Comment by LC43** [comment]
fixed the missing variable and improved detection of older WP  on 22e55f18e8ae3d530279fe75588e1d18f9b17aac

thanks everyone!

ps: re-open if it didn't fix this issue
