### ISSUE TITLE
meta hreflang tags functionality behind qtX

### ISSUE THREAD

**Issue by aga-parts** [not-only-code/qtranslate-slug#134]
An issue with `meta` ` hreflang` tags (for SEO purposes) was fixed in q-translateX version 3.3.3, but not in QTS:

> Fix: hreflang in <link> is now locale instead of language code: [WP Topic](https://wordpress.org/support/topic/setting-hreflang-language-locale).

**Comment by LC43** [comment]
thanks for the report @aga-parts !

closed in recent fix : c35391bb70fc65f5634425d43e220ea48402dc8b
