### ISSUE TITLE
When category is edited, slug column in wp_terms does not change.

### ISSUE THREAD

**Issue by HowToSolutionsNET** [not-only-code/qtranslate-slug#14]
It seems that once category is named, data on **slug** column in **wp_terms** table cannot be changed.

I noticed that when I renamed a category to "news" and the following code did not return anything:

```
$some_query = new WP_Query('category_name=news');
```

I tried to give the same value for all languages (both for the name and the slug) and the above code still did not work.

Using phpMyAdmin I discovered that the **slug** column in **wp_terms** table was still having old original value when category was created.

EDIT

I am thinking maybe this behavior is how it was intended to work.

If this is the case just ignore this issue.

**Comment by not-only-code** [comment]
Hi, i think that happens because translated term slug's are stored on termmeta table instead term table..,

Then must be any point in wp_query when query fails.

I will check this, thanks for your report!
C.

**Comment by LC43** [comment]
going to close this after 1 year. Thanks everyone!
