### ISSUE TITLE
Using the same slug for different pages

### ISSUE THREAD

**Issue by duman** [not-only-code/qtranslate-slug#149]
I have two pages which have the same slug but for different parents.

> Ex:
> /category1/example1
> /education/example1

What I want to do is using the same slug like the above example but it causes duplicate content. How can I achieve this?

There's a post like this: https://kuchenundkakao.wordpress.com/2015/07/15/qtranslate-slug-same-slugs-in-different-hierarchy-on-pages-hierarchical-post-types/ but I'd like a built-in solution for this in the plugin, thank you!

**Comment by kuchenundkakao** [comment]
Sorry, but it seems as if Carlos isn't that active anymore. Can understand it, as the Plugin this was written for originally (qtranslate) as well as the plugins it also supported (mqtranslate, qtranslateX) are not developed or fixed anymore and will stop working/have already stopped working with actual versions of Wordpress. As i wrote the referenced post, i can tell that it should work. Sorry, but that's the best i can give you.

**Comment by duman** [comment]
Thank you for helping.
