### ISSUE TITLE
Duplicate content issue

### ISSUE THREAD

**Issue by rg-** [not-only-code/qtranslate-slug#152]
Hi, i don´t know if somebody notice this, but, ex:

en/some-page/
es/alguna-pagina/

Those will be normal translated page slugs for EN and ES langs, that´s ok. The problem arrives when you type this url:

es/some-page/
Shows the same page es/alguna-pagina/
That´s considered by google as duplicate content.

So, the fix for this i could find is something like this:

`add_action('init', 'app_output_buffer');
function app_output_buffer() {
	ob_start();
}

add_action('wp_head','WPBC_qtranslate_test');
function WPBC_qtranslate_test(){
	global $qtranslate_slug;
	global $q_config; 

	$current_lang = $q_config['language'];
	$default_language = $q_config['default_language']; 
	$url_lang= basename($_SERVER['REQUEST_URI']);  
	$qtranslate_current_url = esc_url($qtranslate_slug->get_current_url( $current_lang ));
	$qtranslate_current_url = str_replace('http:', '', $qtranslate_current_url);
	$qtranslate_current_url = str_replace('https:', '', $qtranslate_current_url);  
	if($default_language!=$current_lang  && !is_404()){
		$test_url = '//'.$_SERVER['SERVER_NAME'].'/'.$current_lang.'/'.$url_lang.'/'; 
		if($qtranslate_current_url!=$test_url){ 
			wp_redirect($qtranslate_current_url,301);
          		exit;
		}
	}
}`

Is a very poor approach but was the only way i could do that.

Basicly, i test if the current url on the REQUEST_URI is the same thay should be, the translated one, if not, i redirect to the correct url, so, if i enter:

es/some-page

it will redirect (301) to

es/alguna-pagina

So, what you thing if anybody see this by the way?

**Comment by kuchenundkakao** [comment]
Hey,
Duplicate content should not be a problem as even when you get the page with the url es/some-page, the canonical tag that is written in the <head> will be es/alguna-pagina.

With the canonical tag, google is told "Hey, disregard the URL, this pages prime URL is this".

So you can remove your filter again. You won't get problems in your google Ranking

**Comment by rg-** [comment]
mmm, yes i understand... anyway i had troubles with that filter in some conditions/cases, too many redirects, you know :)
But, know i´m thinking.. what happens with sitemap.xml in this cases? Google will not take that as duplicate content if in the sitemap there are two urls with same exact content? You know what i mean?

**Comment by rg-** [comment]
Forget about that, i´m using all-in-one-seo-pack with sitemap addon and seems to work ok, no duplicate urls on sitemap :)

Great!
