### ISSUE TITLE
Homepage sends wrong URL for Facebook like (since WP 3.5)

### ISSUE THREAD

**Issue by weigertj** [not-only-code/qtranslate-slug#23]
By updating to Wordpress 3.5 the Facebook like number on my homepage (root URL) became incorrect (the other pages seem fine). I had a look at the source code of my homepage and instead of my main URL I could see my Contact page URL in the the FB like code. Not only in my English version but in all 3 languages.
Thus if somebody pressed the like button on my homepage, he or she liked my Contact page. Currently I use Like-Button-Plugin-For-Wordpress but if I disable it and place the like button code manually, it's still wrong.
I checked Facebook's developer site https://developers.facebook.com/docs/reference/plugins/like/ to get the code manually from there. If I clicked on the Like button even on the FB developer site, FB got the wrong link from my homepage.

By disabling qTranslate-slug OR downgrading to WP 3.4.2 I have the correct link in my source-code and the correct number of Facebook likes on my homepage again.

**Comment by not-only-code** [comment]
Added to 1.1.5

**Comment by kuchenundkakao** [comment]
Please try this: https://kuchenundkakao.wordpress.com/2013/02/15/some-more-bugfixing-for-qtranslate-slug/

**Comment by weigertj** [comment]
I've just updated to the Wordpress 3.5.1. and it by itself solved the problem! I am still using the old qTranslate version 2.5.32. So possibly Worpdress 3.5 caused the bug! I wanted to try your fix kuchenundkakao, but it looks like I won't need it. Thx, anyway!
