### ISSUE TITLE
Title is not shown correctly

### ISSUE THREAD

**Issue by tsjemo** [not-only-code/qtranslate-slug#24]
I did a clean install of WP 3.5, installed qTranslate 2.5.32 and qTranslate slug 1.1, but now the_title() always returns the same content (which is not the current page) & Wordpress SEO (by Yoast de Valk) returns the same content instead of the correct title of the page (I assume it uses the same function the_title() )...

I disabled the qTranslate Slug plugin and the contents is correct (even though then I can't add any language specific slug which is a requirement for my project)... 

Can you help me on this one? Currently the only thing I can do is start from scratch tomorrow (January, 4), installing WP 3.4.2 and start all over again…

**Comment by not-only-code** [comment]
Hi, i think your bug is [this issue](https://github.com/not-only-code/qtranslate-slug/issues/15).

Try to do `wp_reset_query()` before `the_post()` in your template.

If this works i'll close this topic.

**Comment by tsjemo** [comment]
Hi, I updated the page.php from the template (Themeforest - Chalong) as you mentioned but it does not change anything...

**Comment by not-only-code** [comment]
Witch more plugins are you using? Only Wordpress SEO (by Yoast de Valk) ?

**Comment by tsjemo** [comment]
Akismet, Contact Form 7, Link View, Link Category Posts, qTranslate, qTranslate Separate Comments, ThemeFuse Maintenance Mode, Wordpress Backup for Dropbox, Wordpress Popular Posts & Wordpress SEO.

But when I disable qTranslate Slug, the titles are shown correctly...

**Comment by not-only-code** [comment]
Ook, it is normal, because Qtranslate Slug has not been tested with all theese plugins. Sure there is an incompatibility with one or more. Did you try to disable all plugins and only activate qtranslate + qtranslate slug ?

In a clean installation: wp 3.5 + qtranslate 2.5.32 + qtranslate slug 1.1 + twenty eleven, for me works fine.

**Comment by not-only-code** [comment]
wp 3.5 + qtranslate 2.5.32 + qtranslate slug 1.1 + Wordpress SEO by Yoast 1.3.4.1 + twenty eleven, works fine too.

**Comment by tsjemo** [comment]
Hi, I had to be sure that it would be ok today, so I am rebuilding the website from scratch on WP 3.4.2.
You think the issue comes from another plugin or the template? Quite strange as everything was ok on 3.4.2 and disabling qTranslate slug solves the issue...

**Comment by not-only-code** [comment]
Yes i think there is an incompatibility with any plugin or theme. Best way is try it one by one...

**Comment by not-only-code** [comment]
Issue closed until more information

**Comment by francesco1119** [comment]
I had the same problem and I switched from qTranslate to wp-i18n. http://wordpress.org/extend/plugins/wp-i18n/
Now I have no problems and I can edit a different SEO for each language witch means better ranking!
