### ISSUE TITLE
Possible slug validation error

### ISSUE THREAD

**Issue by timersys** [not-only-code/qtranslate-slug#28]
Hi Carlos, thanks for the plugin. Its a totally missed feature of qTranslate.
I have a problem on the site that some urls just wont work.

I tried going to Settings -> Languages -> Uncheck Hide URL language information for default language.

But still the same problem, error 404 (on default language only)

I see the slugs on the post_meta table but i dont see them in the term meta table( which im not sure why you use it).

The site have lot of urls so i havent tested all, just the ones the client says are not working.

If i change the slug from grua to grua-1 for example, it works. If i switch it back to grua it stop working again.

On the termmeta table also secondary language are missing but again im not sure hwo you use this table

**Comment by not-only-code** [comment]
Hi, first of all what wp version are you using? And witch plugins?
For what kind of content it happens? in post/page or taxonomies?
Can you put an example url?

**Comment by timersys** [comment]
Hi!
Im using last version of WP
It happens with posts
Example not working url can be found here http://aristegui.info/es/grua/ 
Working url http://aristegui.info/en/espanol-grua/

I didnt develop this site so im not sure about the code. Plugins could affect are : Taxonomy Meta Version 1.1.4, qTranslate Version 2.5.33b, My Category Order Version 3.3.2 , Gecka Terms Ordering Version 1.0-beta1, Advanced Custom Fields Modified  Version 3.5.8.1

Regards

**Comment by not-only-code** [comment]
In your case i think the problem is you are using the same slug for different levels of navigation and language (could be beacuse this issue https://github.com/not-only-code/qtranslate-slug/issues/4 ), try to add manually the slug per item and language, for example:

http://aristegui.info/es/grua
http://aristegui.info/en/hoist

**Comment by timersys** [comment]
My slugs were configured as:
grua
espanol-grua
francais-grua

The last two are working fine. I changed as you suggested but spanish grua is still not working
Im not using inside branches. It just the default language slug added by qtranslate. ( /es, /en, /fr )

**Comment by not-only-code** [comment]
Try to update your plugin from here, changes maded in [issue#31](https://github.com/not-only-code/qtranslate-slug/issues/31) must solve this.
