### ISSUE TITLE
Call to each of the languages slugs.

### ISSUE THREAD

**Issue by pabloselin** [not-only-code/qtranslate-slug#30]
Hi.
How can I call one or all of the custom translated slugs assigned to a term? Because when you call the usual object (like $term->slug) you get the old non-translated slug. 

Thanks for your plugin.

**Comment by not-only-code** [comment]
Hi there is not a function to get a permalink in other language yet,

but if you want to get the permalink of term in current language **[get_term_link](http://codex.wordpress.org/Function_Reference/get_term_link)** should work.
