### ISSUE TITLE
global $post var changed in _get_page_link and not changed back

### ISSUE THREAD

**Issue by kuchenundkakao** [not-only-code/qtranslate-slug#31]
In the Function _get_page_link the global $post var is changed and not changed back, leading to global $post not working correctly outside of the loop (e.g. to display the post thumbnail in the header)

Further information: 
http://kuchenundkakao.wordpress.com/2013/02/15/some-more-bugfixing-for-qtranslate-slug/

Solution: Make the changes in the function like this:

```
public function _get_page_link( $link, $id ) {
global $post, $wp_rewrite, $q_config;
// Begin Changes: Add temp var for our original post object
$tmp_post = $post;
// End Changes
if ( !$id )
$id = (int) $post->ID;
else
$post = &get_post($id);

$draft_or_pending = in_array( $post->post_status, array( 'draft', 'pending', 'auto-draft' ) );

$link = $wp_rewrite->get_page_permastruct();

if ( !empty($link) && ( isset($post->post_status) && !$draft_or_pending ) ) {

$link = str_replace('%pagename%', $this->get_page_uri($id), $link);

$link = trim($link, '/'); // hack
$link = home_url("/$link/"); // hack

if ($q_config['url_mode'] != 1)
$link = user_trailingslashit($link, 'page');

} else {

$link = home_url("?page_id=$id");
}
// Begin Changes: set the global $post back to the original stored in $tmp_post
$post = $tmp_post;
// End Changes
return $link;
}
```

**Comment by not-only-code** [comment]
Hi, thanks again!

I'm working on a full translation plugin for Wordpress and i have little time to devote to these issues...
Do you want access to commit the code directly? That would be great.

**Comment by kuchenundkakao** [comment]
I just wrote you a message on twitter.
