### ISSUE TITLE
Messes up "Edit Media" -page

### ISSUE THREAD

**Issue by ghost** [not-only-code/qtranslate-slug#32]
Hello,

The plugin is working well. But today I tried to edit some of my uploaded images from my media library and I noticed that "Edit Media" -page is messed up. It looks like this: http://cl.ly/image/090f2M2M0K44

And when I disable the plugin, the page looks like normal: http://cl.ly/image/0o3P2e1N340P

I'm sure that qTranslate Slug causes this issue to happen. I really hope that you could help me with this and find out the reason for this behavior.

Thanks!

**Comment by not-only-code** [comment]
Hello, I am offering minimal support for this plugin ... i will finish its development in version 1.2

WordPress 3.5 did introduce a new media edit page, i don't know what is the problem, but there must be any function  (perhaps File URL) that crash and stops the render of the page... I will take a look this (targeted to 1.2)...

If i found the solution and you dont want to wait to 1.2 maybe we can discuss here the code and change it yourself.

Thanks for report.
C.

**Comment by ghost** [comment]
I think I'll wait for the new version to come out. Hope it isn't too far away... but if you found the solution before the release, that would be superb!

Thanks for all your work!

**Comment by not-only-code** [comment]
Try to update manually your plugin [from here](https://github.com/not-only-code/qtranslate-slug/archive/trunk.zip), and check if this solves your problem.

**Comment by ghost** [comment]
It seems like it's working now. No issues so far! I'll report if I find something.

Thank you!

**Comment by not-only-code** [comment]
Nice! I close this issue :)
