### ISSUE TITLE
qTranslate slug problem - menu can't find pages

### ISSUE THREAD

**Issue by Finkensieper** [not-only-code/qtranslate-slug#33]
We need to use the qTranslate slug plugin to manage our template for WP 3.5.1.

But Menus didn't find existing pages if plugin is enable.
If disable everything works fine.
http://88.217.144.103 show the actual problem.

Any suggestions to fix this problem...
Thanks

**Comment by kuchenundkakao** [comment]
What do you mean by "Menus didn't find existing pages" ?
Please explain further. The Test URL seems to work right now without qtranslate slugs enabled...

**Comment by not-only-code** [comment]
Try to update manually your plugin [from here](https://github.com/not-only-code/qtranslate-slug/archive/trunk.zip), and check if this solves your problem.

**Comment by LC43** [comment]
going to close this after 1 year. Thanks everyone!
