### ISSUE TITLE
[Backend] New tag slug uses post name

### ISSUE THREAD

**Issue by gmaggio** [not-only-code/qtranslate-slug#40]
When adding new tags from the Post Edit page, the **slug** of the new tags uses the sanitized version of the **post name** instead of the tag names.

**Comment by not-only-code** [comment]
Good! Make a push request, could be a good idea merge this part.... what do
you think? I need more time for check all this anyway...

2013/4/14 Giraldi Maggio notifications@github.com

> When adding new tags from the Post Edit page, the _slug_ of the new tags
> uses the sanitized version of the _post name_ instead of the tag names.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/not-only-code/qtranslate-slug/issues/40
> .

## 

Carlos A. Sanz García
t. +34 661 75 18 07
www.behance.net/csg

**Comment by gmaggio** [comment]
I assume you're referring to issue #39. Sure, use the code if it works. Happy to contribute. Take your time and keep up the good work. ;)

**Comment by LC43** [comment]
somewhere between april 2013 and now, it has been fixed. Thanks everyone! :dancer:
