### ISSUE TITLE
New slug not being used in hreflang="" tag

### ISSUE THREAD

**Issue by purpurkitty** [not-only-code/qtranslate-slug#44]
When you choose a different post slug for a secondary language for example, the source code for the default English version of the post still shows the default slug in the hreflang="fr" tag in the source code. 

For example: I have a post with the following English slug: this-is-my-english-post
My French slug is: ceci-est-mon-post-en-francais

The source code for the English version of the post (/this-is-my-english-post/) shows the following for the hreflang="fr": /fr/this-is-my-english-post/

When I go to the /fr/ceci-est-mon-post-en-francais/, it shows the following for hreflang="en": /ceci-est-mon-post-en-francais/

**Comment by LC43** [comment]
this seems to be related to #25

**Comment by LC43** [comment]
fixed in 1.1.8
