### ISSUE TITLE
CSV Importer and qtranslate-slug

### ISSUE THREAD

**Issue by craftycoding** [not-only-code/qtranslate-slug#48]
Hiya,

Having some problems with a 404 error from scheduled posts. I import the posts using CSV (I have now tried two different importing CSV plugins because I thought the first one maybe wasn't importing correctly), and they are all scheduled and look fine but when they publish, they show they are published but going to the page gives me a 404 error. This only appears when I am using qtranslate-slug otherwise it just appears on the blog correctly. I have compared rows in the db and the scheduled ones have the same fields in wp-posts. I can only assume that some qtranslate hook or filter isn't being triggered when the posts are imported rather than saved. Anyone had this problem before? I know this is quite a specific problem but it might help someone else out too ;)

**Comment by LC43** [comment]
does it stil happen? closing it for now, more than 2 years.
