### ISSUE TITLE
Redirect bug

### ISSUE THREAD

**Issue by noref** [not-only-code/qtranslate-slug#49]
http://klmz.rv.ua/portfolio/%D0%BB%D1%8E%D0%BA%D0%B8-%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D1%96%D0%B7%D0%B0%D1%86%D1%96%D0%B9%D0%BD%D1%96/ - OK

http://klmz.rv.ua/portfolio/%D0%BB%D1%8E%D0%BA%D0%B8-%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D1%96%D0%B7%D0%B0%D1%86%D1%96%D0%B9%D0%BD%D1%96 - OK

// Finnishing slash doesn't matter

http://klmz.rv.ua/ru/portfolio/%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BB%D1%8E%D0%BA%D0%B8/ - OK

http://klmz.rv.ua/ru/portfolio/%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BB%D1%8E%D0%BA%D0%B8 - Reidrect to main page //(why?)

Sorry for my english, please.

**Comment by LC43** [comment]
uu, 2013..

we need to properly test utf8 urls...

**Comment by LC43** [comment]
i believe with the new qtranslate-x and with our latest versions, utf8 slugs are working fine. let us know if some issues arise.
