### ISSUE TITLE
Add navs menus to upgrade process

### ISSUE THREAD

**Issue by not-only-code** [not-only-code/qtranslate-slug#5]
Reference:

[http://wordpress.org/support/topic/plugin-qtranslate-slug-backend-menu-language-switcher-doesnt-work?replies=7#post-2980688](http://wordpress.org/support/topic/plugin-qtranslate-slug-backend-menu-language-switcher-doesnt-work?replies=7#post-2980688)

**Comment by LC43** [comment]
i believe this is not an issue anymore.
