### ISSUE TITLE
Problem on IIS server without mod_rewrite

### ISSUE THREAD

**Issue by rumeau** [not-only-code/qtranslate-slug#50]
Hello, i implemented qTranslate a while ago, and now i need to add support for slug localization.

The problem is that this plugin doesnt seem to work well without mod_rewrite.

The urls i had were something like:
http://www.somedomain.com/index.php/customposttype/post-name.html

but when i enable the qTranslate slug plugin my urls are translated without the index.php part:
http://www.somedomain.com/customposttype_translated/post-name.html

The problem is that i cant enable URL rewrite in the server because i dont have access to it.

i tried to add the index.php  part to the translated slug like "index.php/customposttype_translated" but this is stored like "index-phpcustomposttype_translated" because of options filtering.

Is there a way to use this without the rewrite extension on the server, o a workaroud for this?.

Thanks

**Comment by not-only-code** [comment]
Hello, try to disable the 'pretty permalinks' ( admin / settings / permalinks ) and set up the simple language URL mode in qtranslate ( admin / settings / languages, advanced dropdown )

**Comment by LC43** [comment]
closing, more than 2 years.
