### ISSUE TITLE
How to style it

### ISSUE THREAD

**Issue by wocmultimedia** [not-only-code/qtranslate-slug#51]
Hello,
I successfully use your plugin but I have a problem to style it.
Which prefix is correct to be used in css?
I mean for qtranslate I use : 
.qtrans_language_chooser li { display:inline; float:left; margin-right:5px }

.qtrans_language_chooser { list-style-type:none }
But now with your plugin activated I get again the bullet beside the flag and flags in vertical. What are the correct class to add instead of those above?
You can look at my link to understand the problem
http://www.expo2015-italy.com/press/corsi/

Thank you very much for your nice plugin.
Angelo

**Comment by kuchenundkakao** [comment]
Well, you could try looking into the sourcecode of the site to find the correct classname ;)

Or just use 

ul.qts-lang-menu / ul.qts-lang-menu li

Have a nice day ;)

**Comment by wocmultimedia** [comment]
Hello,
I tried to search into the sourcecode but I'm not so experienced neither in wp nor in php. Thanx a lot for helping.

2)Anyhow I found a problem with woocommerce if I make a search using the category name the category changes but the product isn't found. 
Do you know if your plugin is compatible with woocommerce or if it is better to use another ecommerce plugin like EDD to create a multilingual site with your plugin?

Thank you ;-)

---------- Header Originale -----------

Da      : "kuchenundkakao" notifications@github.com
A          : "not-only-code/qtranslate-slug" qtranslate-slug@noreply.github.com
Cc          : "wocmultimedia" info@wocmultimedia.com
Data      : Fri, 05 Jul 2013 23:37:29 -0700
Oggetto : Re: [qtranslate-slug] How to style it (#51)
