### ISSUE TITLE
Cannot logout

### ISSUE THREAD

**Issue by raneri** [not-only-code/qtranslate-slug#56]
I'm using Qtranslate Slug on a live website, so I can't deactivate every plugin that I installed to test it deeper, anyway I found that it seems to have an incompatibility with Theme MY Login. When both plugins are active, clicking on "logout" buttons (both from frontend and admin panel) causes an infinite redirection loop.

To avoid this, I added this piece of code at the beginning of filter_request( $query ), after global $q_config, $wp_query, $wp;

```
    if( isset($query['pagename']) && $query['pagename']=='logout' ){
        return $query;
    }
```

**Comment by not-only-code** [comment]
I've just tweaked this function, let me check if that solves this issue.

**Comment by not-only-code** [comment]
For me works fine, try to use [mqtranslate](https://wordpress.org/plugins/mqtranslate/) and [qtranslate-slug 1.1.7](http://downloads.wordpress.org/plugin/qtranslate-slug.zip)

**Comment by LC43** [comment]
i assume this has been fixed. great!
