### ISSUE TITLE
qtranslate-slug putting duplicate language code into URL

### ISSUE THREAD

**Issue by skolasbn** [not-only-code/qtranslate-slug#58]
ive activated your plugin, when i click on links in my menu i'm getting a url that looks like this:

www.mysiteurl.com/fr/fr/about-us/

please let me know if you have any ideas on this.  Thank you!

**Comment by marcellmars** [comment]
on settings page of qtranslate /wp-admin/options-general.php?page=qtranslate you should see the table with all languages and there is a Edit link for everyone of them. i fixed that by editing the language and deleting everying in Date Format and Time Format. i used it with wordpress 3.8 and it is not ready for 3.8 for sure. a lot of small bugs and annoyances.

**Comment by LC43** [comment]
thanks everyone for reporting and helping. i'm closing this issue!
