### ISSUE TITLE
Improvement suggestions to make a new version

### ISSUE THREAD

**Issue by wocmultimedia** [not-only-code/qtranslate-slug#59]
Hi,

I have a wp 3.8 installation with woocommerce to be used in 2 languages en/it.
I found out a new plugin called qtranslate support for woocommerce.
This plugin is supposed to work with qTranslate and woocommerce but actually it doesn't work completey fine. It has only one slug box for category so by the end it doesn't translate correctly slug category to be used in widget custom menu, while it translate perfectly attribute and variations.
I found out that using both Qtranslate Slug and qtranslate support for woocommerce you can have a good result.

I wish you can find a way to integrate such plugin in your to have one better and simple solution. The plugin project is also on github
https://github.com/mweimerskirch/wordpress-qtranslate-support-for-woocommerce

Regards,
Angelo

**Comment by not-only-code** [comment]
Thanks, that's a good starting point to implement this feature. Linked to issue #7 and close this one.
