### ISSUE TITLE
Conflicting with WooCommerce

### ISSUE THREAD

**Issue by rahilwazir** [not-only-code/qtranslate-slug#60]
Hello I'm facing a problem with `post_type_link` filter.

When i visit woocommerce archive page and click on single product, i get redirected to:
`http://example.com/used-items/%product_cat%/my-item (trigger Bad Request error)`

Instead of: `http://example.com/used-items/product-category/my-item`

My custom permalinks for WooCommerce Product is: `/used-items/%product_cat%`

It doesn't translate the %product_cat% to its actual output (product category slug)

File: **woocommerce-core-functions.php #1422**

```
add_filter( 'post_type_link', 'woocommerce_product_post_type_link', 10, 2 );
```

File: **qtranslate-slug.php #475**

```
add_filter( 'post_type_link',   array($this, 'post_type_link'), 600, 4 );
```

**Fix:**

Incrementing the priority of `post_type_link` filter, it takes the precedence after your `post_type_link` filter.

File: **functions.php**

```
remove_filter( 'post_type_link', 'woocommerce_product_post_type_link', 10, 2 );
add_filter( 'post_type_link', 'woocommerce_product_post_type_link', 601, 2 );
```

**Comment by not-only-code** [comment]
For now qtranslate-slug does not support ecommerce plugins like **Jigoshop** or **Woocommerce**. Anyway this was added as enhancement issue here #7
