### ISSUE TITLE
404 not returned 

### ISSUE THREAD

**Issue by codep0et** [not-only-code/qtranslate-slug#61]
I have a custom post type that is set under slug options to have a different slug in French.  When anything is entered after the slug either in english or french it does not give a 404 but actually a blank page with archive in the title of the page. Eg. Now lets use example.com/en/news/asdasd and example.com/en/actualites/asdasd 

both suppose to return 404 but not working.

**Comment by LC43** [comment]
i believe this is now fixed.  i know its been too long.. sorry!
