### ISSUE TITLE
qtranslate slug 2nd level menu 404 error

### ISSUE THREAD

**Issue by BekirFaruk** [not-only-code/qtranslate-slug#62]
Hello, i am having 404 error when i click to 2nd level menu items. 

example.com/contact is working but if i click example.com/services/someservice i am getting 404 error.

how can i fix it ?

**Comment by kuchenundkakao** [comment]
did you just recently activate qtranslate slug? If yes: you have to save the root level page again, so that the slug information is saved for the rewrite. So you first edit the page "services" and save, then edit the "someservice" page and save again. 

CU, KuK

**Comment by BekirFaruk** [comment]
@kuchenundkakao thanks a lot. the situation was exactly as you told. I have recently activated qtranslate slug. As you said i edit "services" page and saved. Finally it works. Thanks again.
