### ISSUE TITLE
Mqtranslate support

### ISSUE THREAD

**Issue by Lesrad** [not-only-code/qtranslate-slug#63]
Hi, please add support for mqtranslate, a fork of qtranslate.
It seems many users of your plugin have switched over to mqtranslate as it supports WP 3.9 
From: http://wordpress.org/support/topic/please-add-support-for-mqtranslate?replies=2

As of  2.6.2.2 of mqTranslate, we restore support for qTranslate Slug features (broken in previous versions). However, your plugin needs to supports ours.

Can you edit this single line (261) in qtranslate-slug.php by replacing :

return ( version_compare($wp_version, "3.3", "<" ) || !is_plugin_active('qtranslate/qtranslate.php') );

by

return ( version_compare($wp_version, "3.3", "<" ) || (!is_plugin_active('qtranslate/qtranslate.php') && !is_plugin_active('mqtranslate/mqtranslate.php')) );

Thank you

Other notes 
http://wordpress.org/support/topic/qtranslate-slug-selector-unexpected-behaviour?replies=7

**Comment by LC43** [comment]
thanks for the patch. Keep up the good work with mqtranslate!
