### ISSUE TITLE
remove styles from code

### ISSUE THREAD

**Issue by not-only-code** [not-only-code/qtranslate-slug#65]
http://wordpress.org/support/topic/v116-unnecessary-inline-css

**Comment by LC43** [comment]
although i agree with the user comment, this code hasn't changed since 1.0

https://github.com/not-only-code/qtranslate-slug/blame/trunk/qtranslate-slug.php#L2226

**Comment by not-only-code** [comment]
https://github.com/not-only-code/qtranslate-slug/issues/66 is a related issue
