### ISSUE TITLE
Design changes

### ISSUE THREAD

**Issue by luiito** [not-only-code/qtranslate-slug#74]
Hello,

I have a problem with qtranslate slug. In the French language, it has changed the design of the web, while in the rest works fine.

This is the web:
French: https://www.theurbansuites.com/fr/suites-et-appartements/
English: https://www.theurbansuites.com/en/suites-apartments/

Can you help me?

Thank you

**Comment by kuchenundkakao** [comment]
Well,
in line 134 of your themes style.css, theres this:
.fr {
    float: right;
}
And the qtranslate / qtranslate slug adds the language tag to the body class, in this case "fr". So your whole body element gets the style "float: right".

**Comment by luiito** [comment]
Thank you!
