### ISSUE TITLE
Hide menu links with untranslated titles

### ISSUE THREAD

**Issue by arildm** [not-only-code/qtranslate-slug#76]
Some users, me included, need to be able to hide some menu links for some languages. That is typically done by making sure that the linked-to content is not translated to that language, but that is impossible in the case of external/"custom" links. For that case maybe we could have an option in the settings to "Hide menu items whose title is not translated"? (Or it could be default behaviour, but I'm not sure if that is desirable.)

The awkwardly named plugin [qTranslate remove one language menu item](http://wordpress.org/plugins/qtranslate-remove-one-language-menu-item/) is a quick fix to accomplish that behaviour, and it works especially well after adding [this snippet](http://wordpress.org/support/topic/invisible-menu-on-main-language-menu#post-5157627), posted in the plugin's currently only support thread.

(I'm not sure about to what extent this plugin aims to generally fix things with qTranslate, so I hope I'm posting in the right place.)

**Comment by LC43** [comment]
i believe this doesn't happen anymore. feel free to open if you have new other information
