### ISSUE TITLE
Attribute and Terms in woocommerce not translated

### ISSUE THREAD

**Issue by wocmultimedia** [not-only-code/qtranslate-slug#77]
Hello,
I'm using your plugin with mqTranslate and it works perfectly except for the Attribute and Terms (attribute variations) not translated. There's only one box when and if I use quicktags they are shown in the product page. The rest is perfect following your usage instructions. Please, have a look at this product page I just created to test a product with variations, if you click on the flags everything changes correctly with the new language but not attribute and its variation
 http://www.expo2015-italy.com/press/en/product/door-2-keys/
Thanks a lot for spending some minutes in checking it.. I can promote your plugin how best solution in my blogs.
Best Regards,
Angelo

**Comment by LC43** [comment]
sorry, its been a year without any response. woocommerce support is non-existing for now. closing for now. hopefully when qtx and qts merge, there will be enough manpower to fix this.
