### ISSUE TITLE
check for existance

### ISSUE THREAD

**Issue by piffpaffpuff** [not-only-code/qtranslate-slug#78]
wordpress spits out some warnings, because keys arent checked. first line 1653, $term isn't always an object, it can also be a plain string based on the wordpress documentation.

correction:
`
if( is_object( $term ) ) {
$term->name = $meta[$term->name][$lang];
}
`

then on line 1608 check again if the key exists. correction:

`
if (isset($meta[$term->name]) && isset($meta[$term->name][$lang])) {
$term->name = $meta[$term->name][$lang];
}
`

**Comment by LC43** [comment]
thanks @piffpaffpuff! We're reviewing the whole code, and we had already some commit to fix these.

**Comment by LC43** [comment]
fixed in 6311c838636bc1bb2348ccacd932448f55a9f8d6
