### ISSUE TITLE
Pagination does not work

### ISSUE THREAD

**Issue by Siliconsoul** [not-only-code/qtranslate-slug#79]
Apparently there are a few bugs concerning paginations.
When on the front page and you click on older blogs, the language switcher no longer works (empty href).
When in a category and you click on older posts, the language switcher resets the pagination to the first page.
The above occurs in pre-path mode. I have tried query mode but that breaks the url completely with queries in the middle of the url.

**Comment by not-only-code** [comment]
This is the same issue #36 and #1 then i close this one.
