### ISSUE TITLE
Add support for qtranslate plus

### ISSUE THREAD

**Issue by not-only-code** [not-only-code/qtranslate-slug#80]
As mqtranslate. https://wordpress.org/plugins/qtranslate-xp/

**Comment by LC43** [comment]
qtranslate-xp, qtranslate-X and ztranslate change the function names.

**Comment by LC43** [comment]
further insight here: https://wordpress.org/support/topic/revert-the-function-naming-to-the-original-2?replies=5

**Comment by LC43** [comment]
fixed in #85 and then again in 6311c838636bc1bb2348ccacd932448f55a9f8d6
