### ISSUE TITLE
Version 1.1.10 on Wordpress Plugin repo contains old code

### ISSUE THREAD

**Issue by tsparber** [not-only-code/qtranslate-slug#87]
Hi,
for me downloading the latest version 1.1.0 from the Wordpress repo yields to an old version (for eq no qtranslate-x support).
https://downloads.wordpress.org/plugin/qtranslate-slug.1.1.10.zip
Downloading the 1.1.9 version yields to better results (same as this repo).
https://downloads.wordpress.org/plugin/qtranslate-slug.1.1.9.zip

Diff: (Selected line shows compatibility check)
https://gist.github.com/tsparber/ecbb712ac519d04fe3e6#file-gistfile1-diff-L297
Is suspect, that the latest packaged Version is based on something old :)

**Comment by LC43** [comment]
You are right! how did i manage to do this? :/

**Comment by LC43** [comment]
Fixed! :D  thanks @tsparber for helping out! 
https://wordpress.org/plugins/qtranslate-slug/developers/
