### ISSUE TITLE
Changing navigation menus is broken

### ISSUE THREAD

**Issue by tsparber** [not-only-code/qtranslate-slug#92]
Hi,

I noticed, that adding new Pages to a Menu breaks the translation.
Upon saving the now changed menu every old translation gets deleted.

Step 1: Create a new test menu /wp-admin/nav-menus.php
Step 2: Add some pages
![screenshot 2015-01-12 22 29 12](https://cloud.githubusercontent.com/assets/1390036/5712974/30215332-9ab7-11e4-8587-6bb90c67ff0e.png)
Step 3: Add more pages
![screenshot 2015-01-12 22 29 30](https://cloud.githubusercontent.com/assets/1390036/5712986/3e5af926-9ab7-11e4-8a0b-68ee0afd7863.png)
![screenshot 2015-01-12 22 36 45](https://cloud.githubusercontent.com/assets/1390036/5712988/458fc456-9ab7-11e4-93df-3a728cad9018.png)
Step 4: Save Menu
![screenshot 2015-01-12 22 29 40](https://cloud.githubusercontent.com/assets/1390036/5712992/4c8c2e2a-9ab7-11e4-9f2a-efc5fae67653.png)

As you can see only the default language (and the translations of the last item) are preserved.

A workaround is changing the Language to "All Languages" before adding a new Page.
![screenshot 2015-01-12 22 57 05](https://cloud.githubusercontent.com/assets/1390036/5712966/1ece0364-9ab7-11e4-826c-a697f8ed0b64.png)

**Comment by johnclause** [comment]
@tsparber: I do not think it belong to -slug plugin, menu was never translated in any qTranslate\* fork, but it was possible to put []<> encoded translations manually and people were doing it. Which one do you use? I hope the next version [qTranslate-X](https://wordpress.org/plugins/qtranslate-x/) will have it straighten out.

**Comment by johnclause** [comment]
trunk https://github.com/qTranslate-Team/qtranslate-x now has a version 2.9.7b available for testing

**Comment by tsparber** [comment]
@johnclause I do think the described feature is part of the -slug plugin (see https://github.com/not-only-code/qtranslate-slug/blob/trunk/assets/js/qts-nav-menu.js). Using slug the translated Menu items are automatically created.

Not loosing the translations upon adding a new pages would be the only desired fix :+1: :smiley:

**Comment by johnclause** [comment]
Ah, ok, I did not know that, I just did not see it working under qTranslate-X, it removed the translations of other languages except the default one, and I assumed that -slug broke it. Thanks a lot, @tsparber, for letting me know.

Anyway, menu translation support is now available in a native for -X way, namely through the use of Language Switching Buttons. It is not released to public yet, it is on trunk at github (https://github.com/qTranslate-Team/qtranslate-x) and a zip at WP (https://downloads.wordpress.org/plugin/qtranslate-x.2.9.7b.zip).

I would really appreciate if somebody tests it. Meanwhile, I am going to look at -slug more extensively to see how it works and if anything needs to be still adjusted to make it fully compatible with qTranslate-X.

Thanks a lot.

**Comment by johnclause** [comment]
Hi All, I created a pull request: https://github.com/not-only-code/qtranslate-slug/pull/97 which might be all we need, but I am not sure, I am not very fluent on -slug and I might be missing something.

It needs to be tested together with the latest trunk [qTranslate-X](https://github.com/qTranslate-Team/qtranslate-x).

Pedro, I also re-enabled widget back, since it has some new features, which -slug does not have. We will need to merge those widgets properly later. Could you describe the set of new features that you have in yours, which you care to preserve? Maybe open a new issue with that?

**Comment by LC43** [comment]
Hello everyone, thanks for your feedback. Since i'm busy at work, the solution for now is to follow @johnclause PR and  disable our admin menus. Hope to have a sometime during weekend to fix ours.

**Comment by johnclause** [comment]
Could you describe the advantages of -slug interface over native -x way? I never saw it working in my tests and do not really know how it was supposed to be.

-slug was originally designed to support the original qTranslate interface, which  is no longer available in -x. And people seem to love Language Switching Buttons much more over multiple fields for each language on a page. Imagine 40 languages configured, would you want to see 40 lines all at the same time?

Would it make sense to work towards adjusting -slug to support -x's Language Switching Buttons? I looked into it a little bit, and now, after I parted js into different files per page, -slug adjusting does not seem as hard as I thought it would be.

What do you think?

**Comment by LC43** [comment]
we've removed the language meta box in favor of more refined qtx meta box.
