### ISSUE TITLE
two error_log messages spotted when WP_DEBUG is on

### ISSUE THREAD

**Issue by johnclause** [not-only-code/qtranslate-slug#98]
`
PHP Notice:  Undefined variable: html in /wp-content/plugins/qtranslate-slug/includes/class-qtranslate-slug.php on line 2464
`

This one is easy, `$html` indeed may not be assigned before `$html .=` is used. I was going to submit PR as for little imperfection, but then this one

`
PHP Notice:  Undefined variable: termname in /wp-content/plugins/qtranslate-slug/includes/class-qtranslate-slug.php on line 2456
`

I do not know how to fix without deeper investigation. Variable `$termname` does not seem to be defined for real.

**Comment by EmilEriksen** [comment]
I'll add another one `Notice: Undefined index: product in /qtranslate-slug/includes/class-qtranslate-slug.php on line 1017`. Apparently $query[$query['post_type']] is not always defined.

**Comment by LC43** [comment]
@EmilEriksen thanks for reporting, i will look into it!

**Comment by daslicht** [comment]
related: https://github.com/not-only-code/qtranslate-slug/issues/115

**Comment by LC43** [comment]
thanks everybody! i think i've fixed all the notices/warnings. please open a new bug if you find any! your help is really appreciated!
